import React from "react";
import * as BiIcons from "react-icons/bi";
// import * as FaIcons from "react-icons/fa";

export const SidebarData = [
   {
      id: 1,
      title: "Home",
      tClass: "nav_link",
      path: "/home",
      icon: <BiIcons.BiHome />,
   },
   {
      id: 2,
      title: "Dashboard",
      tClass: "nav_link",
      path: "/dashboard/myOrders",
      icon: <BiIcons.BiCollection />,
      iconClosed: <BiIcons.BiChevronDown />,
      iconOpened: <BiIcons.BiChevronUp />,
   },
   {
      id: 3,
      title: "Products",
      tClass: "nav_link",
      path: "/products",
      icon: <BiIcons.BiGridAlt />,
      iconClosed: <BiIcons.BiChevronDown />,
      iconOpened: <BiIcons.BiChevronUp />,
   },
   // {
   //    id: 4,
   //    title: "My Orders",
   //    tClass: "nav_link",
   //    path: "/dashboard/myOrders",
   //    icon: <FaIcons.FaOpencart />,
   //    iconClosed: <BiIcons.BiChevronDown />,
   //    iconOpened: <BiIcons.BiChevronUp />,
   // },
   // {
   //    id: 5,
   //    title: "Analytics",
   //    tClass: "nav_link",
   //    path: "/analytics",
   //    icon: <BiIcons.BiPieChartAlt2 />,
   // },
   // {
   //    id: 6,
   //    title: "Chart",
   //    tClass: "nav_link",
   //    path: "/chart",
   //    icon: <BiIcons.BiLineChart />,
   // },
   // {
   //    id: 7,
   //    title: "Plugins",
   //    tClass: "nav_link",
   //    path: "/plugins",
   //    icon: <BiIcons.BiPlug />,
   //    iconClosed: <BiIcons.BiChevronDown />,
   //    iconOpened: <BiIcons.BiChevronUp />,
   //    subNav: [
   //       {
   //          id: 71,
   //          title: "UI Face",
   //          tClass: "sub_nav_link",
   //          path: "/plugins/plugin1",
   //          icon: <BiIcons.BiFace />,
   //       },
   //       {
   //          id: 72,
   //          title: "Pigments",
   //          tClass: "sub_nav_link",
   //          path: "/plugins/plugin2",
   //          icon: <BiIcons.BiBrush />,
   //       },
   //       {
   //          id: 73,
   //          title: "Box Icons",
   //          tClass: "sub_nav_link",
   //          path: "/plugins/plugin3",
   //          icon: <BiIcons.BiCubeAlt />,
   //       },
   //    ],
   // },
   // {
   //    id: 8,
   //    title: "Explore",
   //    tClass: "nav_link",
   //    path: "/explore",
   //    icon: <BiIcons.BiCompass />,
   // },
   // {
   //    id: 9,
   //    title: "History",
   //    tClass: "nav_link",
   //    path: "/history",
   //    icon: <BiIcons.BiHistory />,
   // },
   {
      id: 10,
      title: "Login",
      tClass: "nav_link",
      path: "/login",
      icon: <BiIcons.BiUserCircle />,
   },
   {
      id: 11,
      title: "Service",
      tClass: "nav_link",
      path: "/settings",
      icon: <BiIcons.BiCog />,
   },
];
